/**
 * Compass CLI — `compass init`.
 *
 * Scaffolds Compass governance into the consumer project at process.cwd():
 *   - compass-tokens-import.md   (GENERATED from this package's app/globals.css)
 *   - .claude/specs/**           (copied, all)
 *   - .claude/skills/**          (copied, all — incl. compass-audit/, compass-migrate/)
 *   - CLAUDE.md                  (copied)
 *   - scripts/token-audit.mjs, scripts/compliance-audit.mjs, scripts/audit-rubric.json
 *   - package.json scripts: audit, audit:compliance (merged, never clobbered)
 *
 * Idempotent: an item whose destination already has identical content reports
 * "already present, skipped". A destination with DIFFERENT content is a
 * CONFLICT — the CLI refuses to overwrite it and exits non-zero after
 * reporting every conflict. --dry-run prints the full plan without writing.
 */

import fs from 'node:fs';
import path from 'node:path';

import { PKG_ROOT, srcPath } from './paths.mjs';

const JUNK_FILES = new Set(['.DS_Store', 'Thumbs.db']);

const COPY_DIRS = [
  { src: '.claude/specs', dest: '.claude/specs' },
  { src: '.claude/skills', dest: '.claude/skills' },
];

const COPY_FILES = [
  { src: 'CLAUDE.md', dest: 'CLAUDE.md' },
  { src: 'scripts/token-audit.mjs', dest: 'scripts/token-audit.mjs' },
  { src: 'scripts/compliance-audit.mjs', dest: 'scripts/compliance-audit.mjs' },
  { src: 'scripts/audit-rubric.json', dest: 'scripts/audit-rubric.json' },
];

const NPM_SCRIPTS = {
  audit: 'node scripts/token-audit.mjs',
  'audit:compliance': 'node scripts/compliance-audit.mjs',
};

const TOKENS_GUIDE_NAME = 'compass-tokens-import.md';

// ─── tokens import guidance (generated, never hand-written) ─────────────────

/**
 * Builds the guidance file from the ACTUAL import chain in this package's
 * app/globals.css — read at run time so it can never drift from source.
 */
function buildTokensGuide() {
  const globalsPath = srcPath('app', 'globals.css');
  const raw = fs.readFileSync(globalsPath, 'utf8');
  const lines = raw.split('\n');
  const importLines = lines.filter((l) => l.trim().startsWith('@import'));
  const variantLines = lines.filter((l) => l.trim().startsWith('@custom-variant'));

  // The fonts.css import is repo-local (Euclid Circular B @font-face) — carry
  // it into the snippet with an explicit note instead of silently dropping it.
  const portable = importLines.filter((l) => !l.includes('./fonts.css'));
  const fontLine = importLines.find((l) => l.includes('./fonts.css'));

  return [
    '# Compass tokens — import chain',
    '',
    '> GENERATED by `compass init` from the Compass package\'s `app/globals.css`.',
    '> Do not hand-edit; re-run `compass init` after upgrading Compass.',
    '',
    'Add these imports to your app\'s global stylesheet (e.g. `app/globals.css`),',
    'in this order:',
    '',
    '```css',
    ...portable,
    ...(variantLines.length > 0 ? ['', ...variantLines] : []),
    '```',
    '',
    ...(fontLine
      ? [
        '## Fonts (manual step)',
        '',
        'The Compass repo additionally imports a local font file:',
        '',
        '```css',
        fontLine,
        '```',
        '',
        '`fonts.css` registers the licensed **Euclid Circular B** family via',
        '`@font-face` (10 .woff2 weights in `app/fonts/`). The font files are',
        'licensed and are NOT distributed by `compass init` — obtain them from',
        'the design team, place them in your app, and register the family under',
        'the exact name `"Euclid Circular B"` (the tokens package resolves font',
        'utilities against that family name at build time).',
        '',
      ]
      : []),
    '## Prerequisites',
    '',
    '- `@acko/enterprise-tokens` (Acko Nexus registry) — the token source.',
    '- Tailwind CSS v4 + `tw-animate-css` + `shadcn` (the import chain above',
    '  references all three).',
    '',
  ].join('\n');
}

// ─── plan building ───────────────────────────────────────────────────────────

/** Recursively lists files under an absolute dir, as paths relative to it. */
function walkFiles(absDir, prefix = '') {
  const out = [];
  for (const entry of fs.readdirSync(absDir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (JUNK_FILES.has(entry.name)) continue;
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...walkFiles(path.join(absDir, entry.name), rel));
    else out.push(rel);
  }
  return out;
}

/** status: "create" | "skip" (identical) | "conflict" (exists, differs) */
function statusOf(destAbs, content) {
  if (!fs.existsSync(destAbs)) return 'create';
  const existing = fs.readFileSync(destAbs);
  return existing.equals(Buffer.isBuffer(content) ? content : Buffer.from(content)) ? 'skip' : 'conflict';
}

/**
 * Builds the full init plan against destRoot. Every planned item carries:
 * { dest (rel), content (Buffer|string), status }.
 */
function buildPlan(destRoot) {
  const items = [];

  // 1. generated tokens guidance
  const guide = buildTokensGuide();
  items.push({
    dest: TOKENS_GUIDE_NAME,
    label: `${TOKENS_GUIDE_NAME} (generated from app/globals.css)`,
    content: guide,
    status: statusOf(path.join(destRoot, TOKENS_GUIDE_NAME), guide),
  });

  // 2-3. spec + skill trees
  for (const { src, dest } of COPY_DIRS) {
    const absSrc = srcPath(src);
    for (const rel of walkFiles(absSrc)) {
      const content = fs.readFileSync(path.join(absSrc, rel));
      const destRel = `${dest}/${rel}`;
      items.push({
        dest: destRel,
        label: destRel,
        content,
        status: statusOf(path.join(destRoot, destRel), content),
      });
    }
  }

  // 4-5. single files
  for (const { src, dest } of COPY_FILES) {
    const content = fs.readFileSync(srcPath(src));
    items.push({
      dest,
      label: dest,
      content,
      status: statusOf(path.join(destRoot, dest), content),
    });
  }

  return items;
}

/** Plans the package.json scripts merge. Returns per-key statuses. */
function planScriptsMerge(destRoot) {
  const pkgPath = path.join(destRoot, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    return { pkgPath, missing: true, entries: [] };
  }
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const scripts = pkg.scripts || {};
  const entries = Object.entries(NPM_SCRIPTS).map(([key, value]) => {
    let status = 'create';
    if (key in scripts) status = scripts[key] === value ? 'skip' : 'conflict';
    return { key, value, existing: scripts[key], status };
  });
  return { pkgPath, missing: false, pkg, entries };
}

// ─── execution ───────────────────────────────────────────────────────────────

const ICON = { create: '+', skip: '=', conflict: '!' };
const WORD = {
  create: 'create',
  skip: 'already present, skipped',
  conflict: 'CONFLICT — exists with different content, refusing to overwrite',
};

export async function runInit({ dryRun = false } = {}) {
  const destRoot = process.cwd();
  console.log(`\ncompass init ${dryRun ? '(dry run — no files will be written)' : ''}`);
  console.log(`  source: ${PKG_ROOT}`);
  console.log(`  target: ${destRoot}\n`);

  if (path.resolve(destRoot) === PKG_ROOT) {
    console.log('  Note: target IS the Compass source root — every item should report "already present".\n');
  }

  const items = buildPlan(destRoot);
  const merge = planScriptsMerge(destRoot);

  // ── report + write files
  let created = 0;
  let skipped = 0;
  const conflicts = [];

  for (const item of items) {
    console.log(`  ${ICON[item.status]} ${item.label} — ${dryRun && item.status === 'create' ? 'would create' : WORD[item.status]}`);
    if (item.status === 'conflict') conflicts.push(item.dest);
    if (item.status === 'skip') skipped++;
    if (item.status === 'create') {
      created++;
      if (!dryRun) {
        const abs = path.join(destRoot, item.dest);
        fs.mkdirSync(path.dirname(abs), { recursive: true });
        fs.writeFileSync(abs, item.content);
      }
    }
  }

  // ── package.json scripts merge
  console.log('\n  package.json scripts:');
  if (merge.missing) {
    console.log('    ! no package.json found in target — run `npm init` first, then re-run compass init.');
    conflicts.push('package.json (missing)');
  } else {
    let mergeNeeded = false;
    for (const e of merge.entries) {
      if (e.status === 'create') {
        mergeNeeded = true;
        console.log(`    ${ICON.create} "${e.key}": "${e.value}" — ${dryRun ? 'would add' : 'added'}`);
      } else if (e.status === 'skip') {
        console.log(`    ${ICON.skip} "${e.key}" — already present, skipped`);
      } else {
        console.log(`    ${ICON.conflict} "${e.key}" — CONFLICT: already set to "${e.existing}", refusing to clobber. `
          + `Rename your script or wire "${e.value}" in manually.`);
        conflicts.push(`package.json scripts.${e.key}`);
      }
    }
    if (mergeNeeded && !dryRun) {
      const pkg = merge.pkg;
      pkg.scripts = pkg.scripts || {};
      for (const e of merge.entries) {
        if (e.status === 'create') pkg.scripts[e.key] = e.value;
      }
      fs.writeFileSync(merge.pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    }
  }

  // ── summary
  console.log(`\n  ${dryRun ? 'plan' : 'done'}: ${created} to create, ${skipped} already present, ${conflicts.length} conflict${conflicts.length === 1 ? '' : 's'}`);
  if (conflicts.length > 0) {
    console.log('\n  Conflicts (nothing was overwritten):');
    for (const c of conflicts) console.log(`    - ${c}`);
    console.log('\n  Resolve these manually (diff against the Compass package copy), then re-run compass init.\n');
    return 1;
  }
  if (!dryRun && created > 0) {
    console.log('\n  Next steps:');
    console.log(`    1. Follow ${TOKENS_GUIDE_NAME} to wire the token imports into your global stylesheet.`);
    console.log('    2. npm run audit            — token discipline gate (zero errors required).');
    console.log('    3. npm run audit:compliance — behavioral audit (advisory scoring).');
    console.log('    4. Open the project in Cursor/Claude Code — CLAUDE.md and .claude/ are picked up automatically.');
  }
  console.log('');
  return 0;
}
